name: 'Amazon ECS "Run Task" Action for GitHub Actions'
description: 'Runs an Amazon ECS task'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The name of ECS task definition'
    required: false
  run-like-service:
    description: 'The name of ECS service to emulate'
    required: false
  cluster:
    description: "The name of the ECS cluster. Will default to the 'default' cluster"
    required: false
  command-override:
    description: "This command overrides the default command from the Docker image or task definition"
    required: false
  container-name:
    description: "The name of the container to receive overrides, only required when using command-override. "
    required: false
  count:
    description: "The count of tasks to run. Will default to the 1"
    required: true
  subnets:
    description: "The subnets to allow this task to run in. Values should be comma separated without spaces"
    required: false
  security-groups:
    description: "The security groups this task should run with. Values should be comma separated without spaces"
    required: false
  started-by:
    description: "The value of the task started-by"
    required: false
  wait-for-finish:
    description: "Whether to wait for tasks to reach stopped state. Will default to not waiting"
    required: false
  wait-for-minutes:
    description: 'How long to wait for the task reach stopped state, in minutes (default: 30 minutes, max: 6 hours).'
    required: false
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  task-arn:
    description: 'The ARN of the ECS task'
runs:
  using: 'node16'
  main: 'dist/index.js'
